//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Finprotest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class alamat_user
    {
        public int almt_Id { get; set; }
        public string alamt_name { get; set; }
        public Nullable<int> zip_code { get; set; }
        public Nullable<int> prov_id { get; set; }
        public Nullable<int> kab_id { get; set; }
        public Nullable<int> country_id { get; set; }
        public string lattitude_user { get; set; }
        public string longitude_user { get; set; }
        public string name_buyer { get; set; }
        public string no_hpbuy { get; set; }
        public Nullable<int> id_user { get; set; }
    }
}
