//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Finprotest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class checkout_user
    {
        public int cout_id { get; set; }
        public Nullable<int> all_total { get; set; }
        public Nullable<int> eks_id { get; set; }
        public Nullable<int> pay_ID { get; set; }
        public Nullable<int> id_user { get; set; }
        public Nullable<int> almt_Id { get; set; }
        public string cout_status { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
    }
}
