//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Finprotest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Deskripsi_product
    {
        public int Deskripsi_id { get; set; }
        public string Deskripsi_isi { get; set; }
        public string Deskripsi_details { get; set; }
        public string Deskripsi_kelebihan { get; set; }
        public Nullable<int> Product_id { get; set; }
    }
}
