//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Finprotest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Image_product
    {
        public int Img_id { get; set; }
        public string img_name { get; set; }
        public Nullable<int> img_numb { get; set; }
        public Nullable<int> Product_id { get; set; }
    }
}
