//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Finprotest.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HakimEntities : DbContext
    {
        public HakimEntities()
            : base("name=HakimEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<account_admin> account_admin { get; set; }
        public virtual DbSet<account_owner> account_owner { get; set; }
        public virtual DbSet<account_user> account_user { get; set; }
        public virtual DbSet<alamat_user> alamat_user { get; set; }
        public virtual DbSet<artist_Db> artist_Db { get; set; }
        public virtual DbSet<Cart_user> Cart_user { get; set; }
        public virtual DbSet<checkout_user> checkout_user { get; set; }
        public virtual DbSet<Deskripsi_product> Deskripsi_product { get; set; }
        public virtual DbSet<Ekspedis_c> Ekspedis_c { get; set; }
        public virtual DbSet<Image_product> Image_product { get; set; }
        public virtual DbSet<KategoriProduct> KategoriProducts { get; set; }
        public virtual DbSet<paymentMethod> paymentMethods { get; set; }
        public virtual DbSet<Product_owner> Product_owner { get; set; }
        public virtual DbSet<Toko_Profil> Toko_Profil { get; set; }
    }
}
