//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Finprotest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pd_group
    {
        public int grp_ID { get; set; }
        public string grp_name { get; set; }
        public Nullable<System.DateTime> Created_at { get; set; }
    }
}
