//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Finprotest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Penjualan_DB
    {
        public int penjualan_id { get; set; }
        public string Char_Name { get; set; }
        public Nullable<int> jumlah_penjualan { get; set; }
    }
}
