//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Finprotest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product_owner
    {
        public int Product_id { get; set; }
        public Nullable<int> Kategori_ID { get; set; }
        public string Product_name { get; set; }
        public string product_img1 { get; set; }
        public string product_img2 { get; set; }
        public string product_img3 { get; set; }
        public Nullable<int> id_owner { get; set; }
        public Nullable<int> product_harga { get; set; }
        public Nullable<int> Product_stock { get; set; }
        public Nullable<int> artist_ID { get; set; }
        public string product_status { get; set; }
    }
}
