//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Finprotest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sw_akses
    {
        public int Akses_ID { get; set; }
        public string akses_name2 { get; set; }
        public string akses_number { get; set; }
        public string lab_akses { get; set; }
        public string tpt_akses { get; set; }
        public string img_akses { get; set; }
        public string file_akses { get; set; }
        public Nullable<int> akse_ID { get; set; }
        public Nullable<System.DateTime> Created_at { get; set; }
    }
}
