//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Finprotest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sw_spt
    {
        public int ch_sptId { get; set; }
        public string ch_sptName { get; set; }
        public string ch_number { get; set; }
        public string ch_frontIMG { get; set; }
        public string ch_sideIMG { get; set; }
        public string ch_BackIMG { get; set; }
        public int Char_Id { get; set; }
        public int sp_id { get; set; }
        public int Type_Id { get; set; }
        public Nullable<System.DateTime> Created_at { get; set; }
    }
}
