//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Finprotest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class swt_prosedata
    {
        public int Proses_DataID { get; set; }
        public string Proses_data { get; set; }
        public string proses_referensi { get; set; }
        public Nullable<int> proses_waktu { get; set; }
        public Nullable<int> proses_frekuensi { get; set; }
        public Nullable<int> ch_sptId { get; set; }
    }
}
