//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Finprotest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class swt_Machine
    {
        public int Machine_ID { get; set; }
        public string Lab_name { get; set; }
        public string Machine_name { get; set; }
        public Nullable<int> proses_waktu { get; set; }
        public Nullable<int> All_Time { get; set; }
        public string pattern_pic { get; set; }
        public Nullable<int> ch_sptId { get; set; }
    }
}
