//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Finprotest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class swt_prosesakses
    {
        public int Prs_aksID { get; set; }
        public string Proses_akses { get; set; }
        public string akses_warna { get; set; }
        public Nullable<int> Banyak_bahan { get; set; }
        public Nullable<int> jumlah_Akses { get; set; }
        public Nullable<int> waktu_akses { get; set; }
        public Nullable<int> Akses_ID { get; set; }
    }
}
