//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Finprotest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class swt_prosesbahan
    {
        public int Proses_ID { get; set; }
        public string Proses_Bahan { get; set; }
        public string Proses_warna { get; set; }
        public Nullable<int> Panjang_baju { get; set; }
        public Nullable<int> Lebar_baju { get; set; }
        public Nullable<int> waktu_baju { get; set; }
        public int ch_sptId { get; set; }
    }
}
