//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Finprotest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class swt_prosesalat
    {
        public int proses_AlatID { get; set; }
        public string Proses_alat { get; set; }
        public string alat_warna { get; set; }
        public int banyak_alat { get; set; }
        public Nullable<int> ch_sptId { get; set; }
    }
}
