//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Finprotest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Toko_Profil
    {
        public int Toko_id { get; set; }
        public string Toko_name { get; set; }
        public string Toko_foto { get; set; }
        public int Kategori_ID { get; set; }
        public string username_owner { get; set; }
        public Nullable<int> id_owner { get; set; }
        public string Toko_long { get; set; }
        public string Toko_lat { get; set; }
        public string Toko_nohp { get; set; }
        public string Toko_bank { get; set; }
        public string Toko_norek { get; set; }
        public string Toko_status { get; set; }
    }
}
